Skipping `generate_test_hlo_checks_test` unit test in the "CPU" test job script
This test is failing in the QA run because QA docker containers are still using Python3.6 instead of Python3.9

The error we get is

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //tensorflow/compiler/xla/service:generate_test_hlo_checks_test
-----------------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/compiler/xla/service/generate_test_hlo_checks_test.runfiles/org_tensorflow/tensorflow/compiler/xla/service/generate_test_hlo_checks_test.py", line 19, in <module>
    from tensorflow.compiler.xla.service import generate_test_hlo_checks
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/compiler/xla/service/generate_test_hlo_checks_test.runfiles/org_tensorflow/tensorflow/compiler/xla/service/generate_test_hlo_checks.py", line 30, in <module>
    class FileCheckVarReplacer:
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/compiler/xla/service/generate_test_hlo_checks_test.runfiles/org_tensorflow/tensorflow/compiler/xla/service/generate_test_hlo_checks.py", line 35, in FileCheckVarReplacer
    _check_instruction_matcher: re.Pattern = re.compile(r"^[^:]*CHECK[^:]*:.*=")
AttributeError: module 're' has no attribute 'Pattern'
```

The `re.Pattern` object used by the test is only present in Python 3.7 and newer.

Also this test has been disabled in upstream develop branch (it has the `no_oss` tag on it).

So simply skipping this test in the `develolp-upstream-QA-rocm50` branch

related JIRA ticket - https://ontrack-internal.amd.com/browse/SWDEV-306738