Fix for SWDEV - 286544
https://ontrack-internal.amd.com/browse/SWDEV-286544

DevOps is running into the following error when trying to build the TF container for 1.15-rocm-enhanced

```
ollecting portpicker
  Downloading portpicker-1.3.9.tar.gz (19 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpy5vcFE
       cwd: /tmp/pip-install-YJo9NI/portpicker
  Complete output (14 lines):
  Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 103, in get_requires_for_build_wheel
      return _get_build_requires(config_settings)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 89, in _get_build_requires
      _run_setup()
    File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 69, in _run_setup
      f = getattr(tokenize, 'open', open)(__file__)
  IOError: [Errno 2] No such file or directory: 'setup.py'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpy5vcFE Check the logs for full command output.
```

This error is a result of attempting to install the Python2.x package for `portpicker`.

Since we no longer do anything with Python2.x, skipping the pip install for Python2.x version of port-picker should be okay ( We use Python3 for our unit testing and produce Python3.x whls )