Fix for TF build failure with ROCm 5.2, due to new templates in rocprim header
ROCm 5.2 staging build 168, started running into the followig build failure for TF

```
...
Execution platform: @local_execution_config_platform//:platform
clang-14: warning: argument unused during compilation: '-fcuda-flush-denormals-to-zero' [-Wunused-command-line-argument]
In file included from tensorflow/core/kernels/histogram_op_gpu.cu.cc:25:
In file included from ./tensorflow/core/kernels/gpu_prim.h:82:
In file included from bazel-out/k8-opt/bin/external/local_config_rocm/rocm/rocm/include/hipcub/hipcub.hpp:36:
In file included from bazel-out/k8-opt/bin/external/local_config_rocm/rocm/rocm/include/hipcub/backend/rocprim/hipcub.hpp:71:
In file included from bazel-out/k8-opt/bin/external/local_config_rocm/rocm/rocm/include/hipcub/backend/rocprim/block/block_histogram.hpp:35:
In file included from bazel-out/k8-opt/bin/external/local_config_rocm/rocm/rocm/include/rocprim/block/block_histogram.hpp:33:
In file included from bazel-out/k8-opt/bin/external/local_config_rocm/rocm/rocm/include/rocprim/block/detail/block_histogram_sort.hpp:32:
In file included from bazel-out/k8-opt/bin/external/local_config_rocm/rocm/rocm/include/rocprim/device/detail/../../block/block_radix_sort.hpp:28:
bazel-out/k8-opt/bin/external/local_config_rocm/rocm/rocm/include/rocprim/device/detail/../../detail/radix_sort.hpp:142:46: error: implicit instantiation of undefined template 'rocprim::detail::float_bit_mask<Eigen::half>'
    static constexpr bit_key_type sign_bit = float_bit_mask<Key>::sign_bit;
                                             ^
./tensorflow/core/kernels/gpu_prim.h:90:7: note: in instantiation of template class 'rocprim::detail::radix_key_codec_floating<Eigen::half, unsigned short>' requested here
    : radix_key_codec_floating<Eigen::half, uint16_t> {};
      ^
bazel-out/k8-opt/bin/external/local_config_rocm/rocm/rocm/include/rocprim/device/detail/../../detail/radix_sort.hpp:99:8: note: template is declared here
...
```

The cause seems to be the introduction of a new template `float_bit_mask` in the rocprim headers.

We need to add explicit instanttiations of that new template for the `Eigen::half` and `Eigen::bfloat16` types, to fix the build failures, which is what this commit does