Fix for SWDEV 296499 - pinning pip version to 21.1.3
As reported in ticket 296499, the `install_python3.6_pip_pacakges.sh` script was running into the following error

```
13:45:22  [91mTraceback (most recent call last):
13:45:22    File "/usr/local/bin/pip3", line 7, in <module>
13:45:22      from pip._internal.cli.main import main
13:45:22    File "/usr/local/lib/python3.6/site-packages/pip/_internal/cli/main.py", line 9, in <module>
13:45:22      from pip._internal.cli.autocompletion import autocomplete
13:45:22    File "/usr/local/lib/python3.6/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
13:45:22      from pip._internal.cli.main_parser import create_main_parser
13:45:22    File "/usr/local/lib/python3.6/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
13:45:22      from pip._internal.cli import cmdoptions
13:45:22    File "/usr/local/lib/python3.6/site-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
13:45:22      from pip._internal.cli.parser import ConfigOptionParser
13:45:22    File "/usr/local/lib/python3.6/site-packages/pip/_internal/cli/parser.py", line 12, in <module>
13:45:22      from pip._internal.configuration import Configuration, ConfigurationError
13:45:22    File "/usr/local/lib/python3.6/site-packages/pip/_internal/configuration.py", line 27, in <module>
13:45:22      from pip._internal.utils.misc import ensure_dir, enum
13:45:22    File "/usr/local/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 38, in <module>
13:45:22      from pip._vendor.tenacity import retry, stop_after_delay, wait_fixed
13:45:22    File "/usr/local/lib/python3.6/site-packages/pip/_vendor/tenacity/__init__.py", line 186, in <module>
13:45:22      class RetryError(Exception):
13:45:22    File "/usr/local/lib/python3.6/site-packages/pip/_vendor/tenacity/__init__.py", line 193, in RetryError
13:45:22      def reraise(self) -> t.NoReturn:
13:45:22  AttributeError: module 'typing' has no attribute 'NoReturn'
13:45:25  [0mThe command '/bin/sh -c tensorflow/tools/ci_build/install/install_python3.6_pip_packages.sh' returned a non-zero code: 1
```

Yanyao found out that pinning the pip version 21.1.3 resolves this error, and hence this change.

An alternate fix would have been to update the Python version from `3.6.1` ro `3.6.9`