Adding `$ROCM_PATH/include[/rocprim,/rocsolver]` as include dirs, in rocm_configure.bzl
ROCm 5.2 staging build 102 introduces changes to location of the HIP runtime header/library files. The previous commit to `rocm_configure.bzl` had updates to address that change. However those changes were not sufficient to get the TensorFlow build to pass. We still got the TF build failure

```
...
...
ERROR: [0m/root/tensorflow/tensorflow/core/kernels/BUILD:4972:18: Compiling tensorflow/core/kernels/sparse_slice_op_gpu.cu.cc failed: undeclared inclusion(s) in rule '//tensorflow/core/kernels:sparse_slice_op_gpu':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/kernels/sparse_slice_op_gpu.cu.cc':
  '/opt/rocm-5.2.0-104/include/rocprim/detail/various.hpp'
  '/opt/rocm-5.2.0-104/include/rocprim/config.hpp'
  '/opt/rocm-5.2.0-104/include/rocprim/types.hpp'
  '/opt/rocm-5.2.0-104/include/rocprim/types/future_value.hpp'
  '/opt/rocm-5.2.0-104/include/rocprim/config.hpp'
  '/opt/rocm-5.2.0-104/include/rocprim/types/double_buffer.hpp'
  '/opt/rocm-5.2.0-104/include/rocprim/types/integer_sequence.hpp'
  '/opt/rocm-5.2.0-104/include/rocprim/types/key_value_pair.hpp'
  '/opt/rocm-5.2.0-104/include/rocprim/types/tuple.hpp'
  '/opt/rocm-5.2.0-104/include/rocprim/detail/all_true.hpp'
  '/opt/rocm-5.2.0-104/include/rocprim/type_traits.hpp'
  '/opt/rocm-5.2.0-104/include/rocprim/types/future_value.hpp'
  '/opt/rocm-5.2.0-104/include/rocprim/intrinsics/warp_shuffle.hpp'
...
...
...
ERROR: /root/tensorflow/tensorflow/core/kernels/linalg/BUILD:134:18: Compiling tensorflow/core/kernels/linalg/cholesky_op_gpu.cu.cc failed: undeclared inclusion(s) in rule '//tensorflow/core/kernels/linalg:cholesky_op_gpu':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/kernels/linalg/cholesky_op_gpu.cu.cc':
  '/opt/rocm-5.2.0-104/include/rocblas.h'
...
...
```

Still need to root cause the above failures, i.e. find out why we are picking up the rocmprim/rocblas/rocsolver headers from the rocm install area, instead of from the local_config_rocm repo (configured by bazel).

In the meantime, working-around this build error can be done easily by adding `$ROCM_PATH/include/rocprim` as an include dir, in rocm_configure.bzl, which is what this commit does.