Updating `rocm_configure.bzl` to account for ROCm 5.2 related header file changes (rccl)
ROCM 5.2 mainline build 9933 introduces changes to the location of the rccl header/libary files, which lead to the following TF build failure.

This commit updates the `rocm_configure.bzl` file to fix that build failure.

```
ERROR: Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/external/local_config_rocm/rocm/BUILD", line 1730, column 8, in <toplevel>
		genrule(
Error in genrule: generated file 'rocm/include/rccl/rccl.h' in rule 'rccl-include' conflicts with existing generated file from rule 'rocm-include', defined at /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/external/local_config_rocm/rocm/BUILD:185:8
INFO: Repository rules_proto instantiated at:
  /root/tensorflow/WORKSPACE:23:14: in <toplevel>
  /root/tensorflow/tensorflow/workspace0.bzl:116:17: in workspace
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/external/bazel_tools/tools/build_defs/repo/http.bzl:364:31: in <toplevel>
ERROR: /root/tensorflow/tensorflow/stream_executor/rocm/BUILD:426:11: errors encountered resolving select() keys for //tensorflow/stream_executor/rocm:all_runtime
ERROR: Analysis of target '//tensorflow/stream_executor/rocm:all_runtime' failed; build aborted:
```